# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: required
cache: packages

# precise fails because unmet deps in libgdal-dev can not be insalled

matrix:
    include:
        - os: linux
          r: release
          dist: trusty
          env: R_CODECOV=true
        - os: linux
          r: devel
          dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change
